GET http://localhost:3333/courses
###
POST  http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDc1MjU2My05NGIyLTRhM2YtODMxMS01NTMzM2QxNzBmNTEiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTU1NDMxNn0.Z6LeZ83rL9qjUE5Erd9A1Kj_vj2kd8uJmnv4fHHU1LU

{
    "title": "Curso de Kubernets"
}
###
GET http://localhost:3333/courses/d4501252-179e-4687-8d58-76c3c070a5e1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YmEyYTM3MC1hZTg0LTRjMTAtYjhhZi01ZDA3NTFhODJkOGYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NTU1MTA2MX0.QeGpnj-7Xp_IZNeLj6f_zWkATHFnxRMLYG8VnS8aykg

###
DELETE http://localhost:3333/courses/a18044a7-4778-4e69-982f-23e58eef4c23
###
PUT http://localhost:3333/courses/149690f0-e02c-4efa-8326-2a90af32bb73
Content-Type: application/json

{
    "title": "Curso de React"
}

####

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "Fabricia.Oliveira25@bol.com.br",
    "password": "Teste@123"
}