GET http://localhost:3333/courses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOTM2YzNhMy1jY2M4LTRlYWMtODYwNS1kNWRkOWE4MDVhYzMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1OTg5Nzk4MH0.7NDVzRIbNo5UHcUTsPb03OIpukjVFobIRXMdB2G3eDE

###
POST  http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjAxYWI1Yi0wZDI0LTRhY2EtOWY2Ny0zOTBjNjViZjNhYzYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1OTg5Nzg3M30.-NDK9qAKpmAJ-EtmfUrEqXEU_Yaec9ueRurFjX7tdE0

{
    "title": "Curso de Go"
}
###
GET http://localhost:3333/courses/d4501252-179e-4687-8d58-76c3c070a5e1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjAxYWI1Yi0wZDI0LTRhY2EtOWY2Ny0zOTBjNjViZjNhYzYiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1OTg5Nzc4Mn0.2Rlq1vcmQE8jTtkjgEDYWiS6jJyHwCwj6FZazueKr9E

###
DELETE http://localhost:3333/courses/a18044a7-4778-4e69-982f-23e58eef4c23
###
PUT http://localhost:3333/courses/149690f0-e02c-4efa-8326-2a90af32bb73
Content-Type: application/json

{
    "title": "Curso de React"
}

####

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "Ricardo_Albuquerque@yahoo.com",
    "password": "Teste@123"
}